{
 "title": "Xwing Site Metrics",
 "tags": [
  "site",
  "memory",
  "cpu",
  "exceptions",
  "locks",
  "threads",
  "web-service",
  "requests"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Environment", "query": "advanced.*" },
   { "name": "Site", "query": "advanced.$Environment.site.*" },
   {
    "name": "Server",
    "query": "advanced.$Environment.site.$Site.*"
   },
   {
    "name": "Instance",
    "query": "advanced.$Environment.site.$Site.$Server.*"
   }
  ]
 },
 "panels": [
  {
   "title": ".NET GC Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(advanced.$Environment.site.$Site.$Server.$Instance._net_clr_memory._total.gen_0_heap_size, 7)"
    },
    {
     "target": "aliasByNode(advanced.$Environment.site.$Site.$Server.$Instance._net_clr_memory._total.gen_1_heap_size, 7)"
    },
    {
     "target": "aliasByNode(advanced.$Environment.site.$Site.$Server.$Instance._net_clr_memory._total.gen_2_heap_size, 7)"
    },
    {
     "target": "aliasByNode(advanced.$Environment.site.$Site.$Server.$Instance._net_clr_memory._total.large_object_heap_size, 7)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(advanced.$Environment.site.$Site.$Server.$Instance.process._total.%_processor_time, 'natasha\\.([^\\.]+)\\.([^\\.]+)\\.([^\\.]+)\\.iis-(i-[^_]+)_([^_]+)_([^\\.]+)\\.([^\\.]+)\\.([^\\.]+)\\.(.+)', '\\4 -- \\8 -- \\9')"
    }
   ]
  },
  {
   "title": "Allocations + Gen 0 GCs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(advanced.$Environment.site.$Site.$Server.$Instance._net_clr_memory._total.allocated_bytes_sec)"
    },
    {
     "target": "aliasByMetric(advanced.$Environment.site.$Site.$Server.$Instance._net_clr_memory._total.#_gen_0_collections)"
    }
   ]
  },
  {
   "title": "Allocations + Gen 1 GCs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(advanced.$Environment.site.$Site.$Server.$Instance._net_clr_memory._total.allocated_bytes_sec)"
    },
    {
     "target": "aliasByMetric(advanced.$Environment.site.$Site.$Server.$Instance._net_clr_memory._total.#_gen_1_collections)"
    }
   ]
  },
  {
   "title": "Allocations + Gen 2 GCs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(advanced.$Environment.site.$Site.$Server.$Instance._net_clr_memory._total.allocated_bytes_sec)"
    },
    {
     "target": "aliasByMetric(advanced.$Environment.site.$Site.$Server.$Instance._net_clr_memory._total.#_gen_2_collections)"
    }
   ]
  },
  {
   "title": "% Time Spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(advanced.$Environment.site.$Site.$Server.$Instance._net_clr_memory._total.%_time_in_gc, 4)"
    }
   ]
  },
  {
   "title": "Pinned GC Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(advanced.$Environment.site.$Site.$Server.$Instance._net_clr_memory._total.#_of_pinned_objects, 4)"
    }
   ]
  },
  {
   "title": "Committed Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(advanced.$Environment.site.$Site.$Server.$Instance._net_clr_memory._total.#_bytes_in_all_heaps)"
    },
    {
     "target": "aliasByMetric(advanced.$Environment.site.$Site.$Server.$Instance._net_clr_memory._total.#_total_committed_bytes)"
    },
    {
     "target": "aliasByMetric(advanced.$Environment.site.$Site.$Server.$Instance.process._total.private_bytes)"
    },
    {
     "target": "aliasByMetric(advanced.$Environment.site.$Site.$Server.$Instance.process._total.working_set)"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(advanced.$Environment.site.$Site.$Server.$Instance.process._total.page_faults_sec)"
    }
   ]
  },
  {
   "title": ".NET Exceptions/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(advanced.$Environment.site.$Site.$Server.$Instance._net_clr_exceptions._total.#_of_exceps_thrown___sec)"
    }
   ]
  },
  {
   "title": ".NET Contentions/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(advanced.$Environment.site.$Site.$Server.$Instance._net_clr_locksandthreads._total.contention_rate___sec)"
    }
   ]
  },
  {
   "title": "Bytes Sent/Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(advanced.$Environment.site.$Site.$Server.$Instance.web_service._total.bytes_sent_sec)"
    },
    {
     "target": "aliasByMetric(advanced.$Environment.site.$Site.$Server.$Instance.web_service._total.bytes_received_sec)"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(advanced.$Environment.site.$Site.$Server.$Instance.w3svc_w3wp._total.active_requests)"
    }
   ]
  }
 ]
}